kind: pipeline
type: kubernetes
name: default
metadata:
  namespace: git
concurrency:
  limit: 1
volumes:
  - name: cache
    claim:
      name: storage2
steps:
  - name: build
    image: docker
    privileged: true
    volumes:
      - name: cache
        path: /cache
    environment:
      TOKEN:
        from_secret: gitea
      TOKEN_DOCKER:
        from_secret: docker_hub
    commands:
      - dockerd --data-root /cache/dockerd &
      - docker login -u voidic -p $TOKEN_DOCKER
      - docker buildx create --platform linux/arm64,linux/amd64 --bootstrap --use
      - docker buildx build --push -t voidic/route96:latest --platform linux/amd64 --platform linux/arm64  .
      - kill $(cat /var/run/docker.pid)
---
kind: pipeline
type: kubernetes
name: docker-tagged
concurrency:
  limit: 1
trigger:
  event:
    - tag
metadata:
  namespace: git
volumes:
  - name: cache
    claim:
      name: storage2
steps:
  - name: build
    image: docker
    privileged: true
    volumes:
      - name: cache
        path: /cache
    environment:
      TOKEN:
        from_secret: gitea
      TOKEN_DOCKER:
        from_secret: docker_hub
    commands:
      - dockerd --data-root /cache/dockerd &
      - docker login -u voidic -p $TOKEN_DOCKER
      - docker buildx build --push voidic/route96:$DRONE_TAG .
      - kill $(cat /var/run/docker.pid)