# Listen address for webserver
listen: "REPLACED_BY_ENV_IN_COMPOSE"

# Database connection string (PostgreSQL)
database: "REPLACED_BY_ENV_IN_COMPOSE"

# Directory to store uploads
storage_dir: "REPLACED_BY_ENV_IN_COMPOSE"

# Maximum support filesize for uploading
max_upload_bytes: 0 # REPLACED_BY_ENV_IN_COMPOSE

# Public facing url
public_url: "REPLACED_BY_ENV_IN_COMPOSE"

# Whitelisted pubkeys, leave out to disable
# whitelist: ["REPLACED_BY_ENV_IN_COMPOSE"]

# Path for ViT(224) image model (https://huggingface.co/google/vit-base-patch16-224)
# vit_model:
#   model: "REPLACED_BY_ENV_IN_COMPOSE"
#   config: "REPLACED_BY_ENV_IN_COMPOSE"

# Analytics support
# plausible_url: "REPLACED_BY_ENV_IN_COMPOSE"

# Support legacy void
# void_cat_database: "REPLACED_BY_ENV_IN_COMPOSE"

# Legacy file path for void.cat uploads
# void_cat_files: "REPLACED_BY_ENV_IN_COMPOSE"

# NIP-29 relay configuration
nip29_relay:
  # communities.nos.social in prod
  url: "REPLACED_BY_ENV_IN_COMPOSE"
  private_key: "REPLACED_BY_ENV_IN_COMPOSE"
  cache_expiration: 0 # REPLACED_BY_ENV_IN_COMPOSE
