# Listen address for webserver
listen: "127.0.0.1:8000"

# Database connection string (MYSQL)
database: "mysql://root:root@localhost:3366/route96"

# Directory to store uploads
storage_dir: "./data"

# Maximum support filesize for uploading
max_upload_bytes: 5e+9

# Public facing url
public_url: "http://localhost:8000"

# (Optional) Whitelisted pubkeys, leave out to disable
# whitelist: ["63fe6318dc58583cfe16810f86dd09e18bfd76aabc24a0081ce2856f330504ed"]

# (Optional) Path for ViT(224) image model (https://huggingface.co/google/vit-base-patch16-224)
# vit_model:
#   model: "falcon_nsfw.safetensors"
#   config: "falcon_nsfw.json"

# (Optional) Analytics support
# plausible_url: "https://plausible.com/"

# (Optional) Legacy file path for void.cat uploads
# void_cat_files: "/my/void.cat/data"

# (Optional) Payment system config
payments:
  # (Optional) Free quota in bytes for users without payments (default: 100MB) 
  free_quota_bytes: 104857600
  # (Optional) Fiat currency used to track exchange rate along with invoices
  # If [cost] is using a fiat currency, exchange rates will always be stored
  # in that currency, so this config is not needed
  fiat: "USD"
  # LND node config
  lnd:
    endpoint: "https://127.0.0.1:10001"
    tls: "/home/kieran/.polar/networks/1/volumes/lnd/alice/tls.cert"
    macaroon: "/home/kieran/.polar/networks/1/volumes/lnd/alice/data/chain/bitcoin/regtest/admin.macaroon"
  # Cost per unit (BTC/USD/EUR/AUD/CAD/JPY/GBP)
  cost:
    currency: "BTC"
    amount: 0.00000100
  # Unit metric used to calculate quote (GBSpace, GBEgress)
  unit: "GBSpace"
  # Billing interval (day / month / year)
  interval:
    month: 1