# Listen address for webserver
listen: "0.0.0.0:8000"

# Specifies which storage backend to use ("FileSystem" or "S3")
# Defaults to FileSystem if not specified.
# storage_type: FileSystem
storage_type: S3

# Database connection string (PostgreSQL)
database: "postgres://postgres:root@db:5432/route96"

# --- Storage Backend Settings ---

# Settings for the FileSystem backend (used if storage_type is FileSystem or omitted)
#filesystem:
  # Directory to store uploads
  #storage_dir: "/app/data"

# Settings for the S3 backend (used if storage_type is S3)
# Requires the 's3-storage' feature flag during compilation.
s3:
  region: "us-east-1" # Optional, defaults to provider default
  endpoint_url: "https://nyc3.digitaloceanspaces.com" # Optional, use for non-AWS S3-compatible storage like DigitalOcean Spaces
  bucket_name: "blossom-test"
  access_key_id: "DO801BJEC2FP8YC8B7XD"
  # Secret key is now set via environment variable APP__S3__SECRET_ACCESS_KEY
  secret_access_key: ""
  force_path_style: false # Optional, default is false. Set to true for some S3-compatible services like MinIO

# Maximum support filesize for uploading
max_upload_bytes: 5242880 # 5 MiB default

# Public facing url
public_url: "http://localhost:8000"

# Whitelisted pubkeys, leave out to disable
# whitelist: ["REPLACED_BY_ENV_IN_COMPOSE"]

# Path for ViT(224) image model (https://huggingface.co/google/vit-base-patch16-224)
# vit_model:
#   model: "REPLACED_BY_ENV_IN_COMPOSE"
#   config: "REPLACED_BY_ENV_IN_COMPOSE"

# Analytics support
# plausible_url: "REPLACED_BY_ENV_IN_COMPOSE"

# Support legacy void
# void_cat_database: "REPLACED_BY_ENV_IN_COMPOSE"

# Legacy file path for void.cat uploads
# void_cat_files: "REPLACED_BY_ENV_IN_COMPOSE"

# NIP-29 relay configuration
nip29_relay:
  # communities.nos.social in prod
  url: "ws://host.docker.internal:8080"
  # This is a test key, replace with your own via environment variables or a local config override.
  # The corresponding public key is 385c3a6ec0b9d57a4330dbd6284989be5bd00e41c535f9ca39b6ae7c521b81cd
  private_key: "6b911fd37cdf5c81d4c0adb1ab7fa822ed253ab0ad9aa18d77257c88b29b718e"
  cache_expiration: 300 # 5 minutes default
