volumes:
  db:
  files:
services:
  db:
    image: mariadb
    environment:
      - "MARIADB_ROOT_PASSWORD=root"
      - "MARIADB_DATABASE=route96"
    volumes:
      - "db:/var/lib/mysql"
  app:
    image: voidic/route96
    #build: .
    # Uncomment and use this build configuration if building locally
    #build:
    #  context: .
    #  args:
    #    # Explicitly specify only the features we need, excluding nip96
    #    FEATURES: "blossom,analytics,ranges,react-ui,r96util"
    environment:
      - "RUST_LOG=info"
    ports:
      - "8000:8000"
    volumes:
      - "files:/app/data"
      - "./config.prod.yaml:/app/config.yaml"
