version: '3.8'

volumes:
  db:
  files:

services:
  db:
    image: postgres:latest
    platform: linux/arm64
    environment:
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_DB=route96"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - "db:/var/lib/postgresql/data"

  app:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile.arm64
      args:
        # Only including essential features:
        # - blossom: Core API functionality
        # - ranges: For better file serving (partial downloads/streaming)
        FEATURES: "blossom,ranges"
    environment:
      RUST_LOG: debug
      # Config values overridden by environment variables - all using double underscores
      APP__LISTEN: 0.0.0.0:8000
      APP__DATABASE: postgres://postgres:root@db:5432/route96
      APP__STORAGE_DIR: /app/data
      APP__MAX_UPLOAD_BYTES: 5000000000
      APP__PUBLIC_URL: http://localhost:8000
      # Nested values with double underscores
      APP__NIP29_RELAY__URL: ws://host.docker.internal:8080
      APP__NIP29_RELAY__PRIVATE_KEY: 6b911fd37cdf5c81d4c0adb1ab7fa822ed253ab0ad9aa18d77257c88b29b718e
      APP__NIP29_RELAY__CACHE_EXPIRATION: 300
    ports:
      - "8000:8000"
    volumes:
      - "files:/app/data"
      - "./config.yaml:/app/config.yaml"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    restart: on-failure
