version: '3.8'

volumes:
  db:
  files:

services:
  db:
    image: postgres:latest
    platform: linux/arm64
    environment:
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_DB=route96"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
      - "RUST_LOG=debug"
      - "POSTGRES_SSL_MODE=require"
    ports:
      - "5432:5432"
    volumes:
      - "db:/var/lib/postgresql/data"
      - "./postgres-ssl-dev:/etc/postgresql/ssl"
    command: postgres -c ssl=on -c ssl_cert_file=/etc/postgresql/ssl/server.crt -c ssl_key_file=/etc/postgresql/ssl/server.key

  app:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile.arm64
      args:
        # Only including essential features:
        # - blossom: Core API functionality
        # - ranges: For better file serving (partial downloads/streaming)
        FEATURES: "blossom,ranges"
    environment:
      # Config values overridden by environment variables - keeping only essential/sensitive ones
      APP__DATABASE: postgres://postgres:root@db:5432/route96?sslmode=require
      APP__STORAGE_DIR: /app/data
      APP__PUBLIC_URL: http://localhost:8000
      # Nested values with double underscores
      APP__NIP29_RELAY__URL: ws://host.docker.internal:8080
      # Test key (pubkey: 385c3a6ec0b9d57a4330dbd6284989be5bd00e41c535f9ca39b6ae7c521b81cd) - replace if needed
      APP__NIP29_RELAY__PRIVATE_KEY: 6b911fd37cdf5c81d4c0adb1ab7fa822ed253ab0ad9aa18d77257c88b29b718e
    ports:
      - "8000:8000"
    volumes:
      - "files:/app/data"
      - "./config.yaml:/app/config.yaml"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    restart: on-failure
