{
 "title": "route96",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Uploaders",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "void_cat",
     "rawSql": "SELECT \n  hex(void_cat.users.pubkey) as pubkey, \n  count(void_cat.user_uploads.file) as uploads, \n  sum(void_cat.uploads.size) as size\nFROM void_cat.users, void_cat.user_uploads, void_cat.uploads\nwhere void_cat.users.id = void_cat.user_uploads.user_id\nand void_cat.user_uploads.file = void_cat.uploads.id\ngroup by void_cat.users.pubkey"
    }
   ]
  },
  {
   "title": "Total Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "select \n  sum(uploads.size) as size\nfrom void_cat.uploads"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "select \n  count(users.pubkey) as users\nfrom void_cat.users"
    }
   ]
  },
  {
   "title": "Total Files",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "select \n  count(uploads.id) as files\nfrom void_cat.uploads"
    }
   ]
  },
  {
   "title": "Latest Uploads",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "select \n  hex(uploads.id) as sha256,\n  hex(users.pubkey) as uploader,\n  uploads.name,\n  sys.format_bytes(uploads.size) as size,\n  uploads.mime_type,\n  uploads.created,\n  uploads.width,\n  uploads.height\nfrom void_cat.uploads, void_cat.user_uploads, void_cat.users\nwhere uploads.id = user_uploads.file\nand users.id = user_uploads.user_id\norder by uploads.created desc\nlimit 50"
    }
   ]
  },
  {
   "title": "Biggest files",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "select \n  hex(uploads.id) as sha256,\n  hex(users.pubkey) as uploader,\n  uploads.name,\n  sys.format_bytes(uploads.size) as size,\n  uploads.mime_type,\n  uploads.created\nfrom void_cat.uploads, void_cat.user_uploads, void_cat.users\nwhere uploads.id = user_uploads.file\nand users.id = user_uploads.user_id\norder by uploads.size desc\nlimit 50"
    }
   ]
  },
  {
   "title": "Most Duplicates",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 26 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "select hex(uf.file) as sha256, count(1) as count\nfrom user_uploads uf\ngroup by uf.file \norder by 2 desc\nlimit 20"
    }
   ]
  }
 ]
}