replicaCount: 3

image:
  repository: nginx
  tag: NA
  pullPolicy: IfNotPresent

pdb:
  minAvailable: 1

autoscaling:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80

persistence:
  size: "1Gi"


service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  host: "blossom.plur.app"