replicaCount: 1

image:
  repository: ghcr.io/verse-pbc/route96
  tag: latest
  pullPolicy: Always

pdb:
  minAvailable: 1

autoscaling:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80

persistence:
  size: "10Gi"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: "nginx"
  host: "blossom.plur.app"
