apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/part-of: {{ .Release.Name }}
    spec:
      containers:
      - name: my-container
        image: nginx
        volumeMounts:
        - name: {{ .Release.Name }}-storage
          mountPath: /data
        # TODO: Specify ports
      volumes:
      - name: {{ .Release.Name }}-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc

#TODO: Add service
#TODO: Add HPA
#TODO: Add PDB
#TODO: Clean template syntax issues and naming.