{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blossom-ingress
  namespace: blossom
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
  labels:
    app.kubernetes.io/part-of: blossom
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blossom-service
                port:
                  number: 80
{{- end -}}