apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blossom-pvc
  namespace: blossom
  labels:
    app.kubernetes.io/part-of: blossom
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: { { .Values.persistence.size | default "1Gi" } }
