apiVersion: v1
kind: Service
metadata:
  name: blossom-service
  namespace: blossom
  labels:
    app.kubernetes.io/part-of: blossom
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: blossom
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP